// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/P2.gold"
import gold.structures.automaton.*;
import gold.util.*;
import gold.visualization.automaton.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class P2 {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=19;
      Object q4_estados=$fix(GCollections.asSet("q4_a","q4_b","q4_c","q4_d","q4_e","q4_f","q4_g","q4_h","q4_i","q4_j","q4_k","q4_l","q4_m","q4_n","q4_o","q4_p","q4_q","q4_r","q4_s","q4_t","q4_u","q4_v","q4_w","q4_x","q4_y","q4_z"));
      $line=22;
      Object Q=$fix($opUnionY($opUnionY(GCollections.asSet("q0","q1","q2","q3"),q4_estados),"err"));
      $line=23;
      Object \u03A3=$fix($opIntvlY('a','z'));
      $line=24;
      Object \u0393=$fix($opIntvlY('a','z'));
      $line=25;
      Object q=$fix("q0");
      $line=26;
      Object F=$fix(Q);
      $line=29;
      Object M=$fix($invokeConstructor(GDeterministicTransducer.class,new Object[]{Q,\u03A3,\u0393,q,F,new GMethod(P2.class,"\u03B4"),new GMethod(P2.class,"g"),new GMethod(P2.class,"h")}));
      $line=32;
      GAutomataFrame.show($cast(gold.structures.automaton.IAutomaton.class,M));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2.class,"main",$line);
    }
  }
  public static Object \u03B4(String q, Object s) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=43;
      Object eAlph=$fix($opIntvlY('a','z'));
      $line=49;
      if ($bool(($bool($opEqualY(q,"q0"))&&$bool($opMembrY(s,eAlph))))) {
        $line=50;
        $result="q1";
        if (true) break $try;
      }
      else {
        $line=56;
        if ($bool(($bool($opEqualY(q,"q1"))&&$bool($opMembrY(s,eAlph))))) {
          $line=57;
          $result="q2";
          if (true) break $try;
        }
        else {
          $line=63;
          if ($bool(($bool($opEqualY(q,"q2"))&&$bool($opMembrY(s,eAlph))))) {
            $line=64;
            $result="q3";
            if (true) break $try;
          }
          else {
            $line=70;
            if ($bool(($bool($opEqualY(q,"q3"))&&$bool($opMembrY(s,eAlph))))) {
              $line=71;
              String q4_nextLetterState=$cast(String.class,$fix($opAdditY("q4_",s)));
              $line=72;
              $result=q4_nextLetterState;
              if (true) break $try;
            }
            else {
              $line=78;
              if ($bool(($bool(((java.lang.String)q).startsWith($cast(java.lang.String.class,"q4_")))&&$opMembrY(s,eAlph)))) {
                $line=79;
                $result="q0";
                if (true) break $try;
              }
              else {
                $line=85;
                $result="err";
                if (true) break $try;
              }
            }
          }
        }
      }
      $line=89;
      $rethrow(new RuntimeException("The function \"\u03B4(q:String,s:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2.class,"\u03B4",$line);
    }
    return $result;
  }
  public static Object h(String q, Object s) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=96;
      Object eAlph=$fix($opIntvlY('a','z'));
      $line=97;
      String alph_str=$cast(String.class,$fix("abcdefghijklmnopqrstuvwxyz"));
      $line=98;
      char[] alph=$cast(char[].class,$fix(((java.lang.String)alph_str).toCharArray()));
      $line=101;
      Character currChar=$cast(Character.class,$fix(s));
      $line=104;
      String duplicateChar=$cast(String.class,$fix($opAdditY(currChar,currChar)));
      $line=107;
      Integer index=$cast(Integer.class,$fix($invokeMethod("indexOf",alph_str,new Object[]{currChar})));
      $line=108;
      Character nextChar=$cast(Character.class,$fix(' '));
      $line=109;
      Character prevChar=$cast(Character.class,$fix(' '));
      $line=110;
      Integer lastPos=$cast(Integer.class,$fix($opSubtrY($invokeField("length",alph),1)));
      $line=113;
      if ($bool($opEqualY(index,0))) {
        $line=114;
        prevChar=$cast(Character.class,$fix(((char[])alph)[$int(lastPos)]));
        $line=115;
        nextChar=$cast(Character.class,$fix(((char[])alph)[$int($opAdditY(index,1))]));
      }
      else {
        $line=116;
        if ($bool($opEqualY(index,lastPos))) {
          $line=117;
          prevChar=$cast(Character.class,$fix(((char[])alph)[$int($opSubtrY(index,1))]));
          $line=118;
          nextChar=$cast(Character.class,$fix(((char[])alph)[$int(0)]));
        }
        else {
          $line=119;
          if ($bool(($bool(!$opEqualY(index,0))&&$bool(!$opEqualY(index,lastPos))))) {
            $line=120;
            prevChar=$cast(Character.class,$fix(((char[])alph)[$int($opSubtrY(index,1))]));
            $line=121;
            nextChar=$cast(Character.class,$fix(((char[])alph)[$int($opAdditY(index,1))]));
          }
        }
      }
      $line=130;
      if ($bool(($opEqualY(q,"q0")&&$opMembrY(s,eAlph)))) {
        $line=131;
        $result=nextChar;
        if (true) break $try;
      }
      else {
        $line=137;
        if ($bool(($opEqualY(q,"q1")&&$opMembrY(s,eAlph)))) {
          $line=138;
          $result=duplicateChar;
          if (true) break $try;
        }
        else {
          $line=144;
          if ($bool(($opEqualY(q,"q2")&&$opMembrY(s,eAlph)))) {
            $line=145;
            $result=prevChar;
            if (true) break $try;
          }
          else {
            $line=151;
            if ($bool(($opEqualY(q,"q3")&&$opMembrY(s,eAlph)))) {
              $line=152;
              $result=s;
              if (true) break $try;
            }
            else {
              $line=158;
              if ($bool(((java.lang.String)q).startsWith($cast(java.lang.String.class,"q4_")))) {
              }
              else {
                $line=166;
                $result="";
                if (true) break $try;
              }
            }
          }
        }
      }
      $line=170;
      $rethrow(new RuntimeException("The function \"h(q:String,s:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2.class,"h",$line);
    }
    return $result;
  }
  public static Object g(Object q) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=177;
      $result="";
      if (true) break $try;
      $line=178;
      $rethrow(new RuntimeException("The function \"g(q:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2.class,"g",$line);
    }
    return $result;
  }
}
