// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/P2_codeDecode.gold"
import gold.*;
import gold.structures.*;
import gold.structures.automaton.*;
import gold.structures.bag.*;
import gold.structures.collection.*;
import gold.structures.deque.*;
import gold.structures.disjointset.*;
import gold.structures.graph.*;
import gold.structures.heap.*;
import gold.structures.list.*;
import gold.structures.map.*;
import gold.structures.multimap.*;
import gold.structures.point.*;
import gold.structures.queue.*;
import gold.structures.set.*;
import gold.structures.stack.*;
import gold.structures.tree.*;
import gold.structures.tree.binary.*;
import gold.structures.tree.nary.*;
import gold.structures.tuple.*;
import gold.structures.turingMachine.*;
import gold.swing.*;
import gold.swing.icon.*;
import gold.swing.icon.ajaxload.*;
import gold.swing.icon.famfamfam.*;
import gold.swing.icon.gold.*;
import gold.swing.icon.jlfgr.*;
import gold.swing.icon.wikimedia.*;
import gold.swing.icon.windows.*;
import gold.swing.look.*;
import gold.swing.util.*;
import gold.test.*;
import gold.test.automaton.*;
import gold.test.general.*;
import gold.test.graph.*;
import gold.util.*;
import gold.visualization.*;
import gold.visualization.automaton.*;
import gold.visualization.graph.*;
import gold.visualization.quadtree.*;
import gold.visualization.turingMachine.*;
import gold.visualization.util.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class P2_codeDecode {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static Object Alphabet=null;
  public static String alph_str=null;
  static {
    int $line=0;
    $line=27;
    $try:try {
      alph_str=$defaultValue(String.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2_codeDecode.class,null,$line);
    }
  }
  public static char[] alph=null;
  static {
    int $line=0;
    $line=28;
    $try:try {
      alph=$defaultValue(char[].class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2_codeDecode.class,null,$line);
    }
  }
  public static Integer lastPos=null;
  static {
    int $line=0;
    $line=29;
    $try:try {
      lastPos=$defaultValue(Integer.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2_codeDecode.class,null,$line);
    }
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=32;
      java.util.Scanner sc=null;
      sc=$invokeConstructor(java.util.Scanner.class,new Object[]{$invokeField(System.class,"in",true,null)});
      $line=34;
      alph_str=$cast(String.class,$fix("abcdefghijklmnopqrstuvwxyz"));
      $line=35;
      alph=$cast(char[].class,$fix(((java.lang.String)alph_str).toCharArray()));
      $line=36;
      lastPos=$cast(Integer.class,$fix($opSubtrY($invokeField("length",alph),1)));
      $line=39;
      Alphabet=$fix($opIntvlY('a','z'));
      $line=42;
      Object coder=$fix(P2_codeDecode.createCoder());
      $line=43;
      Object deCoder=$fix(P2_codeDecode.createDecoder());
      $line=50;
      P2_codeDecode.consoleCodeDecode($cast(gold.structures.automaton.ITransducer.class,coder),$cast(gold.structures.automaton.ITransducer.class,deCoder));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2_codeDecode.class,"main",$line);
    }
  }
  public static Object consoleCodeDecode(ITransducer C, ITransducer D) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=54;
      java.util.Scanner sc=null;
      sc=$invokeConstructor(java.util.Scanner.class,new Object[]{$invokeField(System.class,"in",true,null)});
      $line=55;
      String currentInput=$cast(String.class,$fix(" "));
      $line=57;
      System.out.println($message(new Object[]{"------------------------------------------------------------- "}));
      $line=58;
      System.out.println($message(new Object[]{"Welcome to Proyect 2: Coder-Decoder! \n"}));
      $line=60;
      while (true) {
        if (!(!$opEqualY(currentInput,""))) break;
        $line=62;
        System.out.println($message(new Object[]{"------------------------------------------------------------- "}));
        $line=63;
        System.out.println($message(new Object[]{"Enter the string you want to use (empty stringto exit):"}));
        $line=65;
        if (!$opEqualY(currentInput,"")) {
          $line=67;
          currentInput=$cast(String.class,$fix(((java.util.Scanner)sc).nextLine()));
          $line=70;
          if (!$opEqualY(currentInput,"")) {
            $line=71;
            Object valid=$fix(false);
            $line=72;
            String option=$cast(String.class,$fix(""));
            $line=75;
            while (true) {
              if (!(!$bool(valid))) break;
              $line=76;
              System.out.println($message(new Object[]{""}));
              $line=77;
              System.out.println($message(new Object[]{"What do you want to do with this string?"}));
              $line=78;
              System.out.println($message(new Object[]{"1. code"}));
              $line=79;
              System.out.println($message(new Object[]{"2. decode"}));
              $line=80;
              System.out.println($message(new Object[]{"3. code and decode"}));
              $line=83;
              option=$cast(String.class,$fix(((java.util.Scanner)sc).nextLine()));
              $line=86;
              if ($opMembrY(option,GCollections.asSet("1","2","3"))) {
                $line=87;
                valid=$fix(true);
              }
              else {
                $line=89;
                System.out.println($message(new Object[]{"You didnt select a valid Option, try again. \n"}));
              }
            }
            $line=96;
            String codedString=$cast(String.class,$fix(""));
            $line=97;
            String deCodedString=$cast(String.class,$fix(""));
            $line=98;
            Boolean isAccepted=null;
            isAccepted=$defaultValue(Boolean.class);
            $line=100;
            String codedStrScript=$cast(String.class,$fix("The Coded string was: "));
            $line=101;
            String deCodedStrScript=$cast(String.class,$fix("The DeCoded string was: "));
            $line=106;
            if ($bool(((java.lang.String)option).equals("1"))) {
              $line=107;
              isAccepted=$cast(Boolean.class,$fix(((gold.structures.automaton.ITransducer)C).acceptsString($cast(java.lang.String.class,currentInput))));
              $line=108;
              codedString=$cast(String.class,$fix(((gold.structures.automaton.ITransducer)C).getOutputString()));
              $line=109;
              System.out.println($message(new Object[]{((java.lang.String)codedStrScript).concat($cast(java.lang.String.class,codedString))}));
            }
            else {
              $line=112;
              if ($bool(((java.lang.String)option).equals("2"))) {
                $line=113;
                isAccepted=$cast(Boolean.class,$fix(((gold.structures.automaton.ITransducer)D).acceptsString($cast(java.lang.String.class,currentInput))));
                $line=114;
                deCodedString=$cast(String.class,$fix(((gold.structures.automaton.ITransducer)D).getOutputString()));
                $line=115;
                System.out.println($message(new Object[]{((java.lang.String)deCodedStrScript).concat($cast(java.lang.String.class,deCodedString))}));
              }
              else {
                $line=120;
                isAccepted=$cast(Boolean.class,$fix(((gold.structures.automaton.ITransducer)C).acceptsString($cast(java.lang.String.class,currentInput))));
                $line=121;
                codedString=$cast(String.class,$fix(((gold.structures.automaton.ITransducer)C).getOutputString()));
                $line=122;
                System.out.println($message(new Object[]{((java.lang.String)codedStrScript).concat($cast(java.lang.String.class,codedString))}));
                $line=124;
                isAccepted=$cast(Boolean.class,$fix(((gold.structures.automaton.ITransducer)D).acceptsString($cast(java.lang.String.class,codedString))));
                $line=125;
                deCodedString=$cast(String.class,$fix(((gold.structures.automaton.ITransducer)D).getOutputString()));
                $line=126;
                System.out.println($message(new Object[]{((java.lang.String)deCodedStrScript).concat($cast(java.lang.String.class,deCodedString))}));
                $line=128;
                String isEqual=$cast(String.class,$fix($opAdditY($opAdditY("The input string is ",(($bool(((java.lang.String)currentInput).equals(deCodedString)))?(""):("not "))),"equal to the decoded string")));
                $line=129;
                System.out.println($message(new Object[]{$opAdditY("\n",isEqual)}));
              }
            }
          }
        }
      }
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2_codeDecode.class,"consoleCodeDecode",$line);
    }
    return $result;
  }
  public static ITransducer createCoder() {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=146;
      Object q4_estados=$fix(GCollections.asSet("q4_a","q4_b","q4_c","q4_d","q4_e","q4_f","q4_g","q4_h","q4_i","q4_j","q4_k","q4_l","q4_m","q4_n","q4_o","q4_p","q4_q","q4_r","q4_s","q4_t","q4_u","q4_v","q4_w","q4_x","q4_y","q4_z"));
      $line=149;
      Object Q=$fix($opUnionY(GCollections.asSet("q0","q1","q2","q3","err"),q4_estados));
      $line=150;
      Object \u03A3=$fix(Alphabet);
      $line=151;
      Object \u0393=$fix(Alphabet);
      $line=152;
      Object q=$fix("q0");
      $line=153;
      Object F=$fix(Q);
      $line=156;
      $result=$invokeConstructor(GDeterministicTransducer.class,new Object[]{Q,\u03A3,\u0393,q,F,new GMethod(P2_codeDecode.class,"\u03B4Code"),new GMethod(P2_codeDecode.class,"g"),new GMethod(P2_codeDecode.class,"hCode")});
      if (true) break $try;
      $line=157;
      $rethrow(new RuntimeException("The function \"createCoder()\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2_codeDecode.class,"createCoder",$line);
    }
    return $cast(ITransducer.class,$result);
  }
  public static Object \u03B4Code(String q, Object s) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=164;
      Object eAlph=$fix($opIntvlY('a','z'));
      $line=170;
      if ($bool(($bool($opEqualY(q,"q0"))&&$bool($opMembrY(s,eAlph))))) {
        $line=171;
        $result="q1";
        if (true) break $try;
      }
      else {
        $line=177;
        if ($bool(($bool($opEqualY(q,"q1"))&&$bool($opMembrY(s,eAlph))))) {
          $line=178;
          $result="q2";
          if (true) break $try;
        }
        else {
          $line=184;
          if ($bool(($bool($opEqualY(q,"q2"))&&$bool($opMembrY(s,eAlph))))) {
            $line=185;
            $result="q3";
            if (true) break $try;
          }
          else {
            $line=191;
            if ($bool(($bool($opEqualY(q,"q3"))&&$bool($opMembrY(s,eAlph))))) {
              $line=192;
              String q4_nextLetterState=$cast(String.class,$fix($opAdditY("q4_",s)));
              $line=193;
              $result=q4_nextLetterState;
              if (true) break $try;
            }
            else {
              $line=199;
              if ($bool(($bool(((java.lang.String)q).startsWith($cast(java.lang.String.class,"q4_")))&&$opMembrY(s,eAlph)))) {
                $line=200;
                $result="q0";
                if (true) break $try;
              }
              else {
                $line=206;
                $result="err";
                if (true) break $try;
              }
            }
          }
        }
      }
      $line=210;
      $rethrow(new RuntimeException("The function \"\u03B4Code(q:String,s:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2_codeDecode.class,"\u03B4Code",$line);
    }
    return $result;
  }
  public static Object hCode(String q, Object s) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=217;
      String currCharAsString=$cast(String.class,$fix(Character.toString($cast(char.class,s))));
      $line=218;
      String duplicateChar=$cast(String.class,$fix(((java.lang.String)currCharAsString).concat($cast(java.lang.String.class,Character.toString($cast(char.class,s))))));
      $line=219;
      Character prevChar=$cast(Character.class,$fix(P2_codeDecode.getPrevChar($cast(java.lang.Character.class,s))));
      $line=220;
      Character nextChar=$cast(Character.class,$fix(P2_codeDecode.getNextChar($cast(java.lang.Character.class,s))));
      $line=226;
      if ($bool($opEqualY(q,"q0"))) {
        $line=227;
        $result=nextChar;
        if (true) break $try;
      }
      else {
        $line=233;
        if ($bool($opEqualY(q,"q1"))) {
          $line=234;
          $result=duplicateChar;
          if (true) break $try;
        }
        else {
          $line=240;
          if ($bool($opEqualY(q,"q2"))) {
            $line=241;
            $result=prevChar;
            if (true) break $try;
          }
          else {
            $line=247;
            if ($bool($opEqualY(q,"q3"))) {
              $line=248;
              $result=s;
              if (true) break $try;
            }
            else {
              $line=254;
              if ($bool(((java.lang.String)q).startsWith($cast(java.lang.String.class,"q4_")))) {
                $line=256;
                for (Object $v1:GCollections.unmodifiableCollection(Alphabet)) {
                  Object letter=$v1;
                  $line=257;
                  if ($bool(((java.lang.String)q).endsWith($cast(java.lang.String.class,letter)))) {
                    $line=258;
                    $result=((java.lang.String)currCharAsString).concat($cast(java.lang.String.class,Character.toString($cast(char.class,letter))));
                    if (true) break $try;
                  }
                }
              }
              else {
                $line=266;
                $result="";
                if (true) break $try;
              }
            }
          }
        }
      }
      $line=270;
      $rethrow(new RuntimeException("The function \"hCode(q:String,s:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2_codeDecode.class,"hCode",$line);
    }
    return $result;
  }
  public static ITransducer createDecoder() {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=279;
      Object Q=$fix(GCollections.asSet("d0","d1","d2","d3","d4","d5","d6","err"));
      $line=280;
      Object \u03A3=$fix(Alphabet);
      $line=281;
      Object \u0393=$fix(Alphabet);
      $line=282;
      Object q=$fix("d0");
      $line=283;
      Object F=$fix(Q);
      $line=285;
      $result=$invokeConstructor(GDeterministicTransducer.class,new Object[]{Q,\u03A3,\u0393,q,F,new GMethod(P2_codeDecode.class,"\u03B4Decode"),new GMethod(P2_codeDecode.class,"g"),new GMethod(P2_codeDecode.class,"hDecode")});
      if (true) break $try;
      $line=286;
      $rethrow(new RuntimeException("The function \"createDecoder()\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2_codeDecode.class,"createDecoder",$line);
    }
    return $cast(ITransducer.class,$result);
  }
  public static Object \u03B4Decode(String q, Object s) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=293;
      String stateId=$cast(String.class,$fix("d"));
      $line=296;
      if ($bool((!$bool(((java.lang.String)q).endsWith($cast(java.lang.String.class,6)))&&!$bool(((java.lang.String)q).endsWith($cast(java.lang.String.class,"r")))))) {
        $line=297;
        Integer nextStateNumber=$cast(Integer.class,$fix($opAdditY(Integer.parseInt($cast(java.lang.String.class,$getArrayValue(q,new Object[]{1}))),1)));
        $line=298;
        $result=((java.lang.String)stateId).concat($cast(java.lang.String.class,Integer.toString($int(nextStateNumber))));
        if (true) break $try;
      }
      else {
        $line=301;
        if ($bool(((java.lang.String)q).endsWith($cast(java.lang.String.class,6)))) {
          $line=302;
          $result=((java.lang.String)stateId).concat($cast(java.lang.String.class,"0"));
          if (true) break $try;
        }
        else {
          $line=305;
          $result="err";
          if (true) break $try;
        }
      }
      $line=307;
      $rethrow(new RuntimeException("The function \"\u03B4Decode(q:String,s:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2_codeDecode.class,"\u03B4Decode",$line);
    }
    return $result;
  }
  public static Object hDecode(Object q, Object s) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=314;
      Character prevChar=$cast(Character.class,$fix(P2_codeDecode.getPrevChar($cast(java.lang.Character.class,s))));
      $line=315;
      Character nextChar=$cast(Character.class,$fix(P2_codeDecode.getNextChar($cast(java.lang.Character.class,s))));
      $line=318;
      if ($opEqualY(q,"d0")) {
        $line=319;
        $result=prevChar;
        if (true) break $try;
      }
      else {
        $line=320;
        if ($bool((($opEqualY(q,"d1")||$opEqualY(q,"d4"))||$opEqualY(q,"d5")))) {
          $line=321;
          $result=s;
          if (true) break $try;
        }
        else {
          $line=322;
          if ($opEqualY(q,"d3")) {
            $line=323;
            $result=nextChar;
            if (true) break $try;
          }
          else {
            $line=325;
            $result="";
            if (true) break $try;
          }
        }
      }
      $line=327;
      $rethrow(new RuntimeException("The function \"hDecode(q:Object,s:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2_codeDecode.class,"hDecode",$line);
    }
    return $result;
  }
  public static Object getPrevChar(Character currentChar) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=338;
      Integer index=$cast(Integer.class,$fix($invokeMethod("indexOf",alph_str,new Object[]{currentChar})));
      $line=339;
      $result=(($bool($opEqualY(index,0)))?(((char[])alph)[$int(lastPos)]):(((char[])alph)[$int($opSubtrY(index,1))]));
      if (true) break $try;
      $line=340;
      $rethrow(new RuntimeException("The function \"getPrevChar(currentChar:Character)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2_codeDecode.class,"getPrevChar",$line);
    }
    return $result;
  }
  public static Object getNextChar(Character currentChar) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=347;
      Integer index=$cast(Integer.class,$fix($invokeMethod("indexOf",alph_str,new Object[]{currentChar})));
      $line=348;
      $result=(($bool($opEqualY(index,lastPos)))?(((char[])alph)[$int(0)]):(((char[])alph)[$int($opAdditY(index,1))]));
      if (true) break $try;
      $line=349;
      $rethrow(new RuntimeException("The function \"getNextChar(currentChar:Character)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2_codeDecode.class,"getNextChar",$line);
    }
    return $result;
  }
  public static Object g(Object q) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=356;
      $result="";
      if (true) break $try;
      $line=357;
      $rethrow(new RuntimeException("The function \"g(q:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2_codeDecode.class,"g",$line);
    }
    return $result;
  }
}
