// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/P2_coder.gold"
import gold.structures.automaton.*;
import gold.util.*;
import gold.visualization.automaton.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class P2_coder {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static String alph_str=null;
  static {
    int $line=0;
    $line=18;
    $try:try {
      alph_str=$defaultValue(String.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2_coder.class,null,$line);
    }
  }
  public static char[] alph=null;
  static {
    int $line=0;
    $line=19;
    $try:try {
      alph=$defaultValue(char[].class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2_coder.class,null,$line);
    }
  }
  public static Integer lastPos=null;
  static {
    int $line=0;
    $line=20;
    $try:try {
      lastPos=$defaultValue(Integer.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2_coder.class,null,$line);
    }
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=23;
      alph_str=$cast(String.class,$fix("abcdefghijklmnopqrstuvwxyz"));
      $line=24;
      alph=$cast(char[].class,$fix(((java.lang.String)alph_str).toCharArray()));
      $line=25;
      lastPos=$cast(Integer.class,$fix($opSubtrY($invokeField("length",alph),1)));
      $line=28;
      Object q4_estados=$fix(GCollections.asSet("q4_a","q4_b","q4_c","q4_d","q4_e","q4_f","q4_g","q4_h","q4_i","q4_j","q4_k","q4_l","q4_m","q4_n","q4_o","q4_p","q4_q","q4_r","q4_s","q4_t","q4_u","q4_v","q4_w","q4_x","q4_y","q4_z"));
      $line=31;
      Object Q=$fix($opUnionY(GCollections.asSet("q0","q1","q2","q3"),q4_estados));
      $line=32;
      Object \u03A3=$fix($opIntvlY('a','z'));
      $line=33;
      Object \u0393=$fix($opIntvlY('a','z'));
      $line=34;
      Object q=$fix("q0");
      $line=35;
      Object F=$fix(Q);
      $line=38;
      Object M=$fix($invokeConstructor(GDeterministicTransducer.class,new Object[]{Q,\u03A3,\u0393,q,F,new GMethod(P2_coder.class,"\u03B4"),new GMethod(P2_coder.class,"g"),new GMethod(P2_coder.class,"h")}));
      $line=41;
      GAutomataFrame.show($cast(gold.structures.automaton.IAutomaton.class,M));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2_coder.class,"main",$line);
    }
  }
  public static Object \u03B4(String q, Object s) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=52;
      if ($opEqualY(q,"q0")) {
        $line=53;
        $result="q1";
        if (true) break $try;
      }
      else {
        $line=56;
        if ($opEqualY(q,"q1")) {
          $line=57;
          $result="q2";
          if (true) break $try;
        }
        else {
          $line=60;
          if ($opEqualY(q,"q2")) {
            $line=61;
            $result="q3";
            if (true) break $try;
          }
          else {
            $line=64;
            if ($opEqualY(q,"q3")) {
              $line=65;
              String q4_nextLetterState=$cast(String.class,$fix($opAdditY("q4_",s)));
              $line=66;
              $result=q4_nextLetterState;
              if (true) break $try;
            }
            else {
              $line=69;
              if ($bool(((java.lang.String)q).startsWith($cast(java.lang.String.class,"q4_")))) {
                $line=70;
                $result="q0";
                if (true) break $try;
              }
            }
          }
        }
      }
      $line=74;
      $rethrow(new RuntimeException("The function \"\u03B4(q:String,s:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2_coder.class,"\u03B4",$line);
    }
    return $result;
  }
  public static Object h(String q, Object s) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=82;
      Character currChar=$cast(Character.class,$fix(s));
      $line=83;
      String currCharAsString=$cast(String.class,$fix(Character.toString($cast(char.class,s))));
      $line=86;
      String duplicateChar=$cast(String.class,$fix(((java.lang.String)currCharAsString).concat($cast(java.lang.String.class,currCharAsString))));
      $line=89;
      Character nextChar=$cast(Character.class,$fix(P2_coder.getNextChar($cast(java.lang.Character.class,currChar))));
      $line=90;
      Character prevChar=$cast(Character.class,$fix(P2_coder.getPrevChar($cast(java.lang.Character.class,currChar))));
      $line=93;
      if ($bool($opEqualY(q,"q0"))) {
        $line=94;
        $result=nextChar;
        if (true) break $try;
      }
      else {
        $line=97;
        if ($bool($opEqualY(q,"q1"))) {
          $line=98;
          $result=duplicateChar;
          if (true) break $try;
        }
        else {
          $line=101;
          if ($bool($opEqualY(q,"q2"))) {
            $line=102;
            $result=prevChar;
            if (true) break $try;
          }
          else {
            $line=105;
            if ($bool($opEqualY(q,"q3"))) {
              $line=106;
              $result=s;
              if (true) break $try;
            }
            else {
              $line=109;
              if ($bool(((java.lang.String)q).startsWith($cast(java.lang.String.class,"q4_")))) {
                $line=110;
                for (Object $v1:GCollections.unmodifiableCollection($opIntvlY('a','z'))) {
                  Object letter=$v1;
                  $line=111;
                  if ($bool(((java.lang.String)q).endsWith($cast(java.lang.String.class,letter)))) {
                    $line=112;
                    $result=((java.lang.String)currCharAsString).concat($cast(java.lang.String.class,Character.toString($cast(char.class,letter))));
                    if (true) break $try;
                  }
                }
              }
              else {
                $line=118;
                $result="";
                if (true) break $try;
              }
            }
          }
        }
      }
      $line=122;
      $rethrow(new RuntimeException("The function \"h(q:String,s:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2_coder.class,"h",$line);
    }
    return $result;
  }
  public static Object g(Object q) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=126;
      $result="";
      if (true) break $try;
      $line=127;
      $rethrow(new RuntimeException("The function \"g(q:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2_coder.class,"g",$line);
    }
    return $result;
  }
  public static Object getPrevChar(Character currentChar) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=131;
      $result=(($bool($opEqualY($invokeMethod("indexOf",alph_str,new Object[]{currentChar}),0)))?(((char[])alph)[$int(lastPos)]):(((char[])alph)[$int($opSubtrY($invokeMethod("indexOf",alph_str,new Object[]{currentChar}),1))]));
      if (true) break $try;
      $line=132;
      $rethrow(new RuntimeException("The function \"getPrevChar(currentChar:Character)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2_coder.class,"getPrevChar",$line);
    }
    return $result;
  }
  public static Object getNextChar(Character currentChar) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=135;
      $result=(($bool($opEqualY($invokeMethod("indexOf",alph_str,new Object[]{currentChar}),lastPos)))?(((char[])alph)[$int(0)]):(((char[])alph)[$int($opAdditY($invokeMethod("indexOf",alph_str,new Object[]{currentChar}),1))]));
      if (true) break $try;
      $line=136;
      $rethrow(new RuntimeException("The function \"getNextChar(currentChar:Character)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2_coder.class,"getNextChar",$line);
    }
    return $result;
  }
}
