// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/P2_coder.gold"
import gold.structures.automaton.*;
import gold.util.*;
import gold.visualization.automaton.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class P2_coder {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=21;
      Object q4_estados=$fix(GCollections.asSet("q4_a","q4_b","q4_c","q4_d","q4_e","q4_f","q4_g","q4_h","q4_i","q4_j","q4_k","q4_l","q4_m","q4_n","q4_o","q4_p","q4_q","q4_r","q4_s","q4_t","q4_u","q4_v","q4_w","q4_x","q4_y","q4_z"));
      $line=24;
      Object Q=$fix($opUnionY(GCollections.asSet("q0","q1","q2","q3","err"),q4_estados));
      $line=25;
      Object \u03A3=$fix($opIntvlY('a','z'));
      $line=26;
      Object \u0393=$fix($opIntvlY('a','z'));
      $line=27;
      Object q=$fix("q0");
      $line=28;
      Object F=$fix(Q);
      $line=31;
      Object M=$fix($invokeConstructor(GDeterministicTransducer.class,new Object[]{Q,\u03A3,\u0393,q,F,new GMethod(P2_coder.class,"\u03B4"),new GMethod(P2_coder.class,"g"),new GMethod(P2_coder.class,"h")}));
      $line=34;
      GAutomataFrame.show($cast(gold.structures.automaton.IAutomaton.class,M));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2_coder.class,"main",$line);
    }
  }
  public static Object \u03B4(String q, Object s) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=45;
      Object eAlph=$fix($opIntvlY('a','z'));
      $line=51;
      if ($bool(($bool($opEqualY(q,"q0"))&&$bool($opMembrY(s,eAlph))))) {
        $line=52;
        $result="q1";
        if (true) break $try;
      }
      else {
        $line=58;
        if ($bool(($bool($opEqualY(q,"q1"))&&$bool($opMembrY(s,eAlph))))) {
          $line=59;
          $result="q2";
          if (true) break $try;
        }
        else {
          $line=65;
          if ($bool(($bool($opEqualY(q,"q2"))&&$bool($opMembrY(s,eAlph))))) {
            $line=66;
            $result="q3";
            if (true) break $try;
          }
          else {
            $line=72;
            if ($bool(($bool($opEqualY(q,"q3"))&&$bool($opMembrY(s,eAlph))))) {
              $line=73;
              String q4_nextLetterState=$cast(String.class,$fix($opAdditY("q4_",s)));
              $line=74;
              $result=q4_nextLetterState;
              if (true) break $try;
            }
            else {
              $line=80;
              if ($bool(($bool(((java.lang.String)q).startsWith($cast(java.lang.String.class,"q4_")))&&$opMembrY(s,eAlph)))) {
                $line=81;
                $result="q0";
                if (true) break $try;
              }
              else {
                $line=87;
                $result="err";
                if (true) break $try;
              }
            }
          }
        }
      }
      $line=91;
      $rethrow(new RuntimeException("The function \"\u03B4(q:String,s:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2_coder.class,"\u03B4",$line);
    }
    return $result;
  }
  public static Object h(String q, Object s) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=98;
      Object eAlph=$fix($opIntvlY('a','z'));
      $line=99;
      String alph_str=$cast(String.class,$fix("abcdefghijklmnopqrstuvwxyz"));
      $line=100;
      char[] alph=$cast(char[].class,$fix(((java.lang.String)alph_str).toCharArray()));
      $line=103;
      Character currChar=$cast(Character.class,$fix(s));
      $line=104;
      String currCharAsString=$cast(String.class,$fix(Character.toString($cast(char.class,s))));
      $line=107;
      String duplicateChar=$cast(String.class,$fix(((java.lang.String)currCharAsString).concat($cast(java.lang.String.class,currCharAsString))));
      $line=110;
      Integer index=$cast(Integer.class,$fix($invokeMethod("indexOf",alph_str,new Object[]{currChar})));
      $line=111;
      Character nextChar=$cast(Character.class,$fix(' '));
      $line=112;
      Character prevChar=$cast(Character.class,$fix(' '));
      $line=113;
      Integer lastPos=$cast(Integer.class,$fix($opSubtrY($invokeField("length",alph),1)));
      $line=116;
      if ($bool($opEqualY(index,0))) {
        $line=117;
        prevChar=$cast(Character.class,$fix(((char[])alph)[$int(lastPos)]));
        $line=118;
        nextChar=$cast(Character.class,$fix(((char[])alph)[$int($opAdditY(index,1))]));
      }
      else {
        $line=119;
        if ($bool($opEqualY(index,lastPos))) {
          $line=120;
          prevChar=$cast(Character.class,$fix(((char[])alph)[$int($opSubtrY(index,1))]));
          $line=121;
          nextChar=$cast(Character.class,$fix(((char[])alph)[$int(0)]));
        }
        else {
          $line=122;
          if ($bool(($bool(!$opEqualY(index,0))&&$bool(!$opEqualY(index,lastPos))))) {
            $line=123;
            prevChar=$cast(Character.class,$fix(((char[])alph)[$int($opSubtrY(index,1))]));
            $line=124;
            nextChar=$cast(Character.class,$fix(((char[])alph)[$int($opAdditY(index,1))]));
          }
        }
      }
      $line=133;
      if ($bool(($opEqualY(q,"q0")&&$opMembrY(s,eAlph)))) {
        $line=134;
        $result=nextChar;
        if (true) break $try;
      }
      else {
        $line=140;
        if ($bool(($opEqualY(q,"q1")&&$opMembrY(s,eAlph)))) {
          $line=141;
          $result=duplicateChar;
          if (true) break $try;
        }
        else {
          $line=147;
          if ($bool(($opEqualY(q,"q2")&&$opMembrY(s,eAlph)))) {
            $line=148;
            $result=prevChar;
            if (true) break $try;
          }
          else {
            $line=154;
            if ($bool(($opEqualY(q,"q3")&&$opMembrY(s,eAlph)))) {
              $line=155;
              $result=s;
              if (true) break $try;
            }
            else {
              $line=161;
              if ($bool(($bool(((java.lang.String)q).startsWith($cast(java.lang.String.class,"q4_")))&&$opMembrY(s,eAlph)))) {
                $line=163;
                for (Object $v1:GCollections.unmodifiableCollection(eAlph)) {
                  Object letter=$v1;
                  $line=164;
                  if ($bool(((java.lang.String)q).endsWith($cast(java.lang.String.class,letter)))) {
                    $line=165;
                    $result=((java.lang.String)currCharAsString).concat($cast(java.lang.String.class,Character.toString($cast(char.class,letter))));
                    if (true) break $try;
                  }
                }
              }
              else {
                $line=173;
                $result="";
                if (true) break $try;
              }
            }
          }
        }
      }
      $line=177;
      $rethrow(new RuntimeException("The function \"h(q:String,s:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2_coder.class,"h",$line);
    }
    return $result;
  }
  public static Object g(Object q) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=184;
      $result="";
      if (true) break $try;
      $line=185;
      $rethrow(new RuntimeException("The function \"g(q:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2_coder.class,"g",$line);
    }
    return $result;
  }
}
