// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/P2_decoder.gold"
import gold.structures.automaton.*;
import gold.util.*;
import gold.visualization.automaton.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class P2_decoder {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=21;
      Object Q=$fix(GCollections.asSet("d0","d1","d2","d3","d4","d5","d6","err"));
      $line=22;
      Object \u03A3=$fix($opIntvlY('a','z'));
      $line=23;
      Object \u0393=$fix($opIntvlY('a','z'));
      $line=24;
      Object q=$fix("d0");
      $line=25;
      Object F=$fix(Q);
      $line=28;
      Object M=$fix($invokeConstructor(GDeterministicTransducer.class,new Object[]{Q,\u03A3,\u0393,q,F,new GMethod(P2_decoder.class,"\u03B4"),new GMethod(P2_decoder.class,"g"),new GMethod(P2_decoder.class,"h")}));
      $line=31;
      GAutomataFrame.show($cast(gold.structures.automaton.IAutomaton.class,M));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2_decoder.class,"main",$line);
    }
  }
  public static Object \u03B4(String q, Object s) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=40;
      Object alphabet=$fix($opIntvlY('a','z'));
      $line=41;
      String stateId=$cast(String.class,$fix("d"));
      $line=44;
      if ($bool(($bool((!$bool(((java.lang.String)q).endsWith($cast(java.lang.String.class,6)))&&!$bool(((java.lang.String)q).endsWith($cast(java.lang.String.class,"r")))))&&$opMembrY(s,alphabet)))) {
        $line=45;
        Integer nextStateNumber=$cast(Integer.class,$fix($opAdditY(Integer.parseInt($cast(java.lang.String.class,$getArrayValue(q,new Object[]{1}))),1)));
        $line=46;
        $result=((java.lang.String)stateId).concat($cast(java.lang.String.class,Integer.toString($int(nextStateNumber))));
        if (true) break $try;
      }
      else {
        $line=49;
        if ($bool(($bool(((java.lang.String)q).endsWith($cast(java.lang.String.class,6)))&&$opMembrY(s,alphabet)))) {
          $line=50;
          $result=((java.lang.String)stateId).concat($cast(java.lang.String.class,"0"));
          if (true) break $try;
        }
        else {
          $line=54;
          $result="err";
          if (true) break $try;
        }
      }
      $line=56;
      $rethrow(new RuntimeException("The function \"\u03B4(q:String,s:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2_decoder.class,"\u03B4",$line);
    }
    return $result;
  }
  public static Object h(Object q, Object s) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=62;
      $result="";
      if (true) break $try;
      $line=63;
      $rethrow(new RuntimeException("The function \"h(q:Object,s:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2_decoder.class,"h",$line);
    }
    return $result;
  }
  public static Object g(Object q) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=69;
      $result="";
      if (true) break $try;
      $line=70;
      $rethrow(new RuntimeException("The function \"g(q:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2_decoder.class,"g",$line);
    }
    return $result;
  }
}
