// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/P2_decoder.gold"
import gold.structures.automaton.*;
import gold.util.*;
import gold.visualization.automaton.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class P2_decoder {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=21;
      Object Q=$fix(GCollections.asSet("d0","d1","d2","d3","d4","d5","d6","err"));
      $line=22;
      Object \u03A3=$fix($opIntvlY('a','z'));
      $line=23;
      Object \u0393=$fix($opIntvlY('a','z'));
      $line=24;
      Object q=$fix("d0");
      $line=25;
      Object F=$fix(Q);
      $line=28;
      Object M=$fix($invokeConstructor(GDeterministicTransducer.class,new Object[]{Q,\u03A3,\u0393,q,F,new GMethod(P2_decoder.class,"\u03B4"),new GMethod(P2_decoder.class,"g"),new GMethod(P2_decoder.class,"h")}));
      $line=31;
      GAutomataFrame.show($cast(gold.structures.automaton.IAutomaton.class,M));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2_decoder.class,"main",$line);
    }
  }
  public static Object \u03B4(String q, Object s) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=39;
      Object alphabet=$fix($opIntvlY('a','z'));
      $line=40;
      String stateId=$cast(String.class,$fix("d"));
      $line=43;
      if ($bool(($bool((!$bool(((java.lang.String)q).endsWith($cast(java.lang.String.class,6)))&&!$bool(((java.lang.String)q).endsWith($cast(java.lang.String.class,"r")))))&&$opMembrY(s,alphabet)))) {
        $line=44;
        Integer nextStateNumber=$cast(Integer.class,$fix($opAdditY(Integer.parseInt($cast(java.lang.String.class,$getArrayValue(q,new Object[]{1}))),1)));
        $line=45;
        $result=((java.lang.String)stateId).concat($cast(java.lang.String.class,Integer.toString($int(nextStateNumber))));
        if (true) break $try;
      }
      else {
        $line=48;
        if ($bool(($bool(((java.lang.String)q).endsWith($cast(java.lang.String.class,6)))&&$opMembrY(s,alphabet)))) {
          $line=49;
          $result=((java.lang.String)stateId).concat($cast(java.lang.String.class,"0"));
          if (true) break $try;
        }
        else {
          $line=53;
          $result="err";
          if (true) break $try;
        }
      }
      $line=55;
      $rethrow(new RuntimeException("The function \"\u03B4(q:String,s:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2_decoder.class,"\u03B4",$line);
    }
    return $result;
  }
  public static Object h(Object q, Object s) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=61;
      String alph_str=$cast(String.class,$fix("abcdefghijklmnopqrstuvwxyz"));
      $line=62;
      char[] alph=$cast(char[].class,$fix(((java.lang.String)alph_str).toCharArray()));
      $line=65;
      Integer index=$cast(Integer.class,$fix($invokeMethod("indexOf",alph_str,new Object[]{s})));
      $line=66;
      Character nextChar=$cast(Character.class,$fix(' '));
      $line=67;
      Character prevChar=$cast(Character.class,$fix(' '));
      $line=68;
      Integer lastPos=$cast(Integer.class,$fix($opSubtrY($invokeField("length",alph),1)));
      $line=71;
      if ($opEqualY(index,0)) {
        $line=72;
        prevChar=$cast(Character.class,$fix(((char[])alph)[$int(lastPos)]));
        $line=73;
        nextChar=$cast(Character.class,$fix(((char[])alph)[$int($opAdditY(index,1))]));
      }
      else {
        $line=74;
        if ($opEqualY(index,lastPos)) {
          $line=75;
          prevChar=$cast(Character.class,$fix(((char[])alph)[$int($opSubtrY(index,1))]));
          $line=76;
          nextChar=$cast(Character.class,$fix(((char[])alph)[$int(0)]));
        }
        else {
          $line=77;
          if (!$opEqualY(index,0)) {
            $line=78;
            prevChar=$cast(Character.class,$fix(((char[])alph)[$int($opSubtrY(index,1))]));
            $line=79;
            nextChar=$cast(Character.class,$fix(((char[])alph)[$int($opAdditY(index,1))]));
          }
        }
      }
      $line=84;
      if ($opEqualY(q,"d0")) {
        $line=85;
        $result=prevChar;
        if (true) break $try;
      }
      else {
        $line=86;
        if ($bool((($opEqualY(q,"d1")||$opEqualY(q,"d4"))||$opEqualY(q,"d5")))) {
          $line=87;
          $result=s;
          if (true) break $try;
        }
        else {
          $line=88;
          if ($opEqualY(q,"d3")) {
            $line=89;
            $result=nextChar;
            if (true) break $try;
          }
          else {
            $line=91;
            $result="";
            if (true) break $try;
          }
        }
      }
      $line=93;
      $rethrow(new RuntimeException("The function \"h(q:Object,s:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2_decoder.class,"h",$line);
    }
    return $result;
  }
  public static Object g(Object q) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=99;
      $result="";
      if (true) break $try;
      $line=100;
      $rethrow(new RuntimeException("The function \"g(q:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P2_decoder.class,"g",$line);
    }
    return $result;
  }
}
